### ISSUE TITLE
Huge memory grab

### ISSUE THREAD

**Issue by casilingua** [Airmail/Airmail_Public#371]
Using 1.3.2 with OS X Mavericks 10.9.3 (13D12) causes Airmail to grab a massive portion of RAM, such that - it happens while watching - the available RAM can go down from 7.40 GB say on an MBP to 350MB with attendant warnings that freeze everything up. This happens on an Air too and another MBP I have, and with the latest 1.4 Beta, so it doesn't seem to be something that's solved. Are you aware of this?

**Comment by hinder90** [comment]
I am still seeing this going on, but it comes in the form of Airmail2 on Mavericks using every last bit of available CPU. I did finally settle down but it still won't quit because it is 'pending operations. I am also noticing that edits to what mailboxes and smart folders I can see keep reverting back to the way they were on the iOS version  before I started. When looking at Operations on the OS X version I see that a "Mark" operation is running on about 850 messages but I have no idiea what it could be, All of my rules should all be on the Google side only so I am not sure what these are about.
